apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: threescale-dev
spec:
  destination:
    namespace: 3scale-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 3scale/app
    repoURL: https://github.com/msakho/3scale-gitops-1.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
